label: Teaser-Text
description: "Ein kurzer Beschreibungstext, der den Inhalt oder Zweck des Teasers näher erklärt. Wir empfehlen einen kurzen Satz, da der Platz in den Tesern je nach Layout begrenzt.<br />\r\n<strong>Leer lassen, um eine gekürzte Version der Seitenbeschreibung zu verwenden.</strong>"
